version: '2'
services:
    node:
        build: .
        env_file: .env
        volumes:
        - .:/code
        ports:
        - "5000:5000"

# Reference
# https://docs.docker.com/compose/gettingstarted/
